export { default as PhonenumOTP } from "./PhonenumOTP";
export { default as Dashboard } from "./Dashboard";
export { default as HomeLayout } from "./HomeLayout";
export { default as Register } from "./Register";
export { default as Logout } from "./Logout";
export { default as Profile} from "./Profile";
export { default as NewsComponent} from "./News";
export { default as CurrencyConverter} from "./Currency";
export { default as MapWithRoute } from "./Navigate";
export {default as AmenitiesFinder} from "./Amenities";
export { default as Login } from "./Login";
export { default as Landing } from "./Landing";
export { default as TandC } from "./T&C";
export { default as Help } from "./HelpManual";
export { default as SecurityQuestion } from "./SecurityQ";
export { default as EditProfile} from "./EditProfile";
export { default as ChangePhoneNumber} from "./ChangePhNum";
export { default as ProfilePic} from "./ProfilePic";
export { default as ChangePassword} from "./ChangePassword";
export { default as ResetPassword} from "./ResetPassword";
export { default as Settings } from "./Settings";
export { default as QuickLinks } from "./QuickLinks";